---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:

  - name: cargo fmt
    image: rustdocker/rust:nightly
    commands:
      - /root/.cargo/bin/cargo fmt -- --check

  - name: cargo check
    image: rust:1.61-bullseye
    commands:
      - cargo check --all --all-targets

  - name: cargo clippy
    image: rust:1.61-bullseye
    commands:
      - rustup component add clippy
      - cargo clippy --workspace --tests --all-targets --all-features -- -D warnings -D deprecated -D clippy::perf -D clippy::complexity -D clippy::dbg_macro
      - cargo clippy --workspace -- -D clippy::unwrap_used

  - name: cargo test
    image: rust:1.61-bullseye
    environment:
      RUST_BACKTRACE: 1
    commands:
      - cargo test --workspace --no-fail-fast

  - name: cargo run
    image: rust:1.61-bullseye
    environment:
      RUST_BACKTRACE: 1
    commands:
      - cargo run -p activitypub_federation --example federation
