---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:

  - name: cargo fmt
    image: rustdocker/rust:nightly
    commands:
      - /root/.cargo/bin/cargo fmt -- --check

  - name: cargo check
    image: rust:1.65-bullseye
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo check --all-features --all-targets

  - name: cargo clippy
    image: rust:1.65-bullseye
    environment:
      CARGO_HOME: .cargo
    commands:
      - rustup component add clippy
      - cargo clippy --all-targets --all-features --
        -D warnings -D deprecated -D clippy::perf -D clippy::complexity
        -D clippy::dbg_macro -D clippy::inefficient_to_string
        -D clippy::items-after-statements -D clippy::implicit_clone
        -D clippy::wildcard_imports -D clippy::cast_lossless
        -D clippy::manual_string_new -D clippy::redundant_closure_for_method_calls
      - cargo clippy --all-features -- -D clippy::unwrap_used

  - name: cargo test
    image: rust:1.65-bullseye
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo test --all-features --no-fail-fast

  - name: cargo doc
    image: rust:1.65-bullseye
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo doc --all-features

  - name: cargo run actix example
    image: rust:1.65-bullseye
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo run --example simple_federation --features actix-web

  - name: cargo run axum example
    image: rust:1.65-bullseye
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo run --example simple_federation --features axum
