---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:

  - name: cargo fmt
    image: rustdocker/rust:nightly
    commands:
      - /root/.cargo/bin/cargo fmt -- --check

  - name: cargo check
    image: clux/muslrust:1.59.0
    commands:
      - cargo check

  - name: cargo clippy
    image: clux/muslrust:1.59.0
    commands:
      - rustup component add clippy
      - cargo clippy --workspace --tests --all-targets --all-features -- -D warnings -D deprecated -D clippy::perf -D clippy::complexity -D clippy::dbg_macro
      - cargo clippy --workspace -- -D clippy::unwrap_used

  - name: cargo test
    image: clux/muslrust:1.59.0
    environment:
      RUST_BACKTRACE: 1
    commands:
      - cargo test --workspace --no-fail-fast
