[package]
name = "activitypub_federation"
version = "0.2.0"
edition = "2021"
description = "High-level Activitypub framework"
license = "AGPL-3.0"
repository = "https://github.com/LemmyNet/activitypub-federation-rust"

[workspace]
members = ["derive"]

[dependencies]
activitypub_federation_derive = { version = "0.2.0", path = "derive" }
chrono = { version = "0.4.19", features = ["clock"], default-features = false }
serde = { version = "1.0.137", features = ["derive"] }
async-trait = "0.1.56"
url = { version = "2.2.2", features = ["serde"] }
serde_json = { version = "1.0.81", features = ["preserve_order"] }
anyhow = "1.0.57"
reqwest = { version = "0.11.10", features = ["json"] }
reqwest-middleware = "0.1.6"
tracing = "0.1.34"
base64 = "0.13.0"
openssl = "0.10.40"
once_cell = "1.12.0"
http = "0.2.8"
sha2 = "0.10.2"
actix-web = { version = "4.0.1", default-features = false }
http-signature-normalization-actix = { version = "0.6.1", default-features = false, features = ["server", "sha-2"] }
http-signature-normalization-reqwest = { version = "0.6.0", default-features = false, features = ["sha-2", "middleware"] }
background-jobs = "0.12.0"
thiserror = "1.0.31"
derive_builder = "0.11.2"
itertools = "0.10.3"

[dev-dependencies]
activitystreams-kinds = "0.2.1"
rand = "0.8.5"
actix-rt = "2.7.0"
tokio = "1.19.2"
env_logger = { version = "0.9.0", default-features = false }
